### ISSUE TITLE
重复播放、停止播放多次后报网络断开

### ISSUE THREAD

**Issue by senselesscn** [LiteAVSDK/Live_Android#17]
重复播放、停止播放多次后报网络断开，附件为复现demo，项目中有Readme文件，记录了复现步骤，并附有录屏和设备信息

SDK版本: com.tencent.liteav:LiteAVSDK_Live:latest.release

机型及版本: Mi 10 Lite Zoom

附件：https://senseless.cn/static/100016133684.zip

**Comment by senselesscn** [comment]
log：https://senseless.cn/static/1000161336-log.zip

**Comment by MinTate** [comment]
好的，已提单到内部，正在分析~

**Comment by MinTate** [comment]
> log：https://senseless.cn/static/1000161336-log.zip

Hello，问题已经定位，是切换到https导致的，10.6版本我们已经修复了这个问题，默认播放http-flv的流，可以在这里下载最新的版本：https://cloud.tencent.com/document/product/454/7873
